### ISSUE TITLE
Session.is_activeでエラー

### ISSUE THREAD

**Issue by kokuzawa** [baykraft/time-recorder#8]
下記エラーが発生する。

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.7/site-packages/slackbot/dispatcher.py", line 55, in _dispatch_msg_handler
    func(Message(self._client, msg), *args)
  File "/app/src/plugins/mentions.py", line 71, in sign_in
    if session.is_active():
TypeError: 'bool' object is not callable
```

**Comment by kokuzawa** [comment]
is_activeはis_active()と呼び出すのではなく、is_activeと呼び出すのが正しい。
